### ISSUE TITLE
Minimize builds

### ISSUE THREAD

**Issue by caniszczyk** [twitter/twitter-cldr-rb#148]
Do we really need to build on everything, even 1.8?

language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2.2.7
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx-2.2.7
    - rvm: jruby-head

**Comment by caniszczyk** [comment]
I ask because the build takes a long time now

**Comment by KL-7** [comment]
JRuby and Rubinius were added just to see how we perform on them (out of curiosity). Ruby 1.8.7 still gives me a warm feel of nostalgia, but it might make sense to retire it already. Though, I think that should include not only dropping it from the build matrix, but also removing all the little hacks we have for 1.8.7 in our code and releasing a new version that officially supports only Ruby 1.9+.

So, I'd say:

1.8.7 – stop supporting it and then remove from the matrix
1.9.3 – still an official stable version of Ruby, keep it
2.0.0 – still an official stable version of Ruby, keep it
2.1.0 – replace with 2.2.0 or w/e the latest version is
rbx and jruby – I'd rather keep them, but if build time is a concern (I didn't experience too much troubles with it), then we can drop them

**Comment by camertron** [comment]
Ruby 1.8.7 is really only supported because we used to use twitter-cldr-rb in the Monorail™. It's definitely time to retire support for it, so I agree with @KL-7's assessment.

I've seen a few annoying issues with JRuby builds, most often with incompatibilities in the YAML parser. I'd like to maintain support for it because I think it's a runtime a lot of people use. We just need to put in a little work to make the tests pass on Travis.

**Comment by camertron** [comment]
Rubinius builds have been removed from the build matrix and we're tracking JRuby failures via #124. Going to close this issue.
