### ISSUE TITLE
Currencies out of date

### ISSUE THREAD

**Issue by shaicoleman** [twitter/twitter-cldr-rb#222]
The currency information is out of date, and is missing the following currency codes: BYN/MRU/STN/VES  (UYW is also missing, but it's not in CLDR 35.1)

**Comment by camertron** [comment]
Hey @shaicoleman, thanks for reporting. I'm in the process of working on updating the library to CLDR v35.1 and hoping to have it ready by the end of the week (time permitting, of course).

**Comment by shaicoleman** [comment]
You'd might to want to hold on for another two weeks or so. CLDR 36 seems to be around the corner.

**Comment by camertron** [comment]
@shaicoleman yeah I see that coming down the pike. I'm hoping v36 won't be a huge breaking change.

**Comment by shaicoleman** [comment]
CLDR 36 is out now

**Comment by camertron** [comment]
@shaicoleman looks like just the beta?

**Comment by shaicoleman** [comment]
Sorry, the release is tagged in git, but not yet available for download

**Comment by shaicoleman** [comment]
It's available for download now

**Comment by camertron** [comment]
Yeah, just saw it on their Github releases page. Will look into it!

**Comment by camertron** [comment]
@shaicoleman The build for my `cldr35` branch is finally passing, so I looked into updating to v36. Unfortunately the update is not trivial. The data set contains a number of vertical arrow characters now (i.e. "↑↑↑") that I don't see mentioned anywhere in the documentation. The mysterious arrows appear to replace existing data, so upgrading will not be straightforward. Rather than delay a release any further by introducing v36, I'm going to release TwitterCLDR v5.0 with CLDR v35.1 data for now, and work on the v36 upgrade later. I would appreciate any help you or others are willing to offer towards that goal. Please let me know if the `cldr35` branch works for your use-case. If not, I'll leave this issue open.

**Comment by shaicoleman** [comment]
`cldr35` branch looks good

**Comment by camertron** [comment]
@shaicoleman just published v5.0.0 of the gem. Happy localizing :)
