### ISSUE TITLE
Ruby 2.7+ compatibility issue/question

### ISSUE THREAD

**Issue by jasonpenny** [twitter/twitter-cldr-rb#250]
https://github.com/twitter/twitter-cldr-rb#compatibility says `TwitterCLDR is fully compatible with Ruby 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0.` but there is a line still using `BigDecimal.new`
(which was deprecated and is now removed in ruby 2.7+ https://github.com/ruby/bigdecimal/blob/master/CHANGES.md#200)

https://github.com/twitter/twitter-cldr-rb/blob/36ae2d7d71f5cfb71f04834f86a68c869376f4ca/lib/twitter_cldr/formatters/numbers/rbnf/rule_set.rb#L102

The full specs do not ever hit this line of code, and it looks like it would only be hit for a rbnf MASTER rule, and I do not see any MASTER rules defined in `resources/` (searching for `:value: x.0`).

My question is, should I open a PR that changes `BigDecimal.new()` -> `BigDecimal()`, or can someone more familiar with this code remove the dead functionality?

**Comment by camertron** [comment]
Hey @jasonpenny, thanks for bringing this up. Unfortunately I don't remember enough about this code to recall when the fractional rules get invoked, and it appears there aren't any tests that cover any fractional numbers (I believe that's because the lib didn't support them originally). In any case, I think we have to consider this codepath as possible. Let's just change `BigDecimal.new(...)` to `BigDecimal(...)` which appears to work in all supported Ruby versions.
