### ISSUE TITLE
Why use :one instead of :name

### ISSUE THREAD

**Issue by ur5us** [twitter/twitter-cldr-rb#253]
https://github.com/twitter/twitter-cldr-rb/blob/a1bf5d0207fd7a9e763fa7e8f2a91d15cd0a0e99/lib/twitter_cldr/shared/currencies.rb#L22

Is there a reason why `for_code(:EUR, :en)` returns `{…, :name=>"euro", …}` instead of `name=>"Euro"` as per the locale’s yml file?

**Comment by camertron** [comment]
Hey @ur5us, thanks for bringing this up. It looks like this code is old enough that it predates the `name` field being available in the CLDR data set. Here's the [currencies.yml file for English](https://github.com/twitter/twitter-cldr-rb/blob/ee8d5b2f023cfc811699be78af17821a162453ac/resources/locales/en/currencies.yml) from 2012.

It should be ok to update the code to use `:name` instead of `:one`, would you care to submit a pull request?
