### ISSUE TITLE
`format: :long` breaks when combined with currency formatting

### ISSUE THREAD

**Issue by stesen-wefunder** [twitter/twitter-cldr-rb#259]
**Describe the bug**
Combining `to_currency` with `format: :long` produces broken output. Specifically, it seems to truncate to the thousands and not abbreviate at all.

**To Reproduce**
Examples:
```rb
5_000_000_000.localize('en').to_currency.to_s(currency: 'USD', format: :long)
# Expected: '$5 billion'
# Actual: '$5,000.00'

5_000_000_000.localize('es').to_currency.to_s(currency: 'USD', format: :long)
# Expected: something like '5 mil millones $'
# Actual: '5.000,00 $'
```

**Comment by camertron** [comment]
Hey @stesen-wefunder, thanks for bringing this to my attention. It looks like the CLDR data set doesn't define any long [currency formats](https://github.com/unicode-org/cldr/blob/618bfe176a3ab8f9aaed0fbc177d64019679db27/common/main/en.xml#L4611) at all - I wasn't able to find them for any language. There is a `:short` format however:

```ruby
5_000_000_000.localize('en').to_currency.to_s(currency: 'USD', format: :short)
# "$5.00T"
```

That said, TwitterCLDR should default to something a lot more reasonable than "$5,000.00". I tracked down the root cause but unfortunately fixing it is going to mean a rewrite of the number formatting code, which I don't have time for right now. My advice for now is to use `format: :short` or the default.

**Comment by stesen-wefunder** [comment]
Hi! Thanks for looking into this!

Thankfully we only use this in one or two places so it's not a big deal. My current very imperfect workaround has been this:
```rb
# Format 0 to normal currency, format the actual number to long with no currency formatting (which works),
# and then gsub 0 for the real formatted number.
# This will break for languages that don't use Arabic numerals
# and might put the currency symbol in the wrong place,
# but this is legitimately the best thing I can think of.
currency_format = 0.localize(@locale).to_currency.to_s(currency: currency, precision: 0)
formatted_amount = @val.localize(@locale).to_s(format: :long, precision: precision)
currency_format.gsub('0', formatted_amount)
```

Yeah would you look at that, I guess that really isn't in the dataset. Huh.
```js
new Intl.NumberFormat("en", {style: "currency", currency: "USD", notation: "compact", compactDisplay: "long"}).format(5_000_000_000)
// '$5B'

new Intl.NumberFormat("en", {notation: "compact", compactDisplay: "long"}).format(5_000_000_000)
// '5 billion'
```

**Comment by stesen-wefunder** [comment]
Ohhh, I hadn't connected the dots (or filed an issue at the time), but I'm guessing this is the same root cause as this behavior I've run into before?
```rb
50_000.localize('de').to_s(format: :short) # => '5'
```

This happens for (at least) `de` and `it`, both of which only have "short" formats starting from the millions.

**Comment by camertron** [comment]
Yeah that looks very similar 😅 Gotta love the inconsistencies in the CLDR.
